
export const metadata = {
    title: "Registeration Page",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body suppressHydrationWarning>{children}</body>
      </html>
    );
  }
  